### ISSUE TITLE
GitHub: Expose API Path as Setting

### ISSUE THREAD

**Issue by WorldMaker** [Inedo/bmx-git#22]
*Suggestion from a past life where I hacked this once already but couldn't send a PR. I figured I'd record the idea for y'all in case you want to implement yourselves.*

If you make the GitHub API Path a setting on the repository it allows people to choose between public GitHub and GitHub for Enterprises installations.

**Comment by jrasch** [comment]
This is a good idea, we will implement this at some point, likely as soon as someone who is using GitHub for Enterprises - should be a relatively quick change.
