### ISSUE TITLE
Feature Request: Git Submodules

### ISSUE THREAD

**Issue by kmcgain** [Inedo/bmx-git#29]
Having git submodules loaded as part of the Get-Labeled-Source operation would be very useful. Given submodules are not a feature across the board for source providers perhaps it should by default load them, or alternatively control the preference from the provider configuration on a per repository basis.

I'm happy to do a PR but wanted to discuss the potential feature.

Currently the workaround is to just load the submodule as a separate repository and then copy the files in manually or just use git directly.

**Comment by stevedennis** [comment]
Part of our "v5 vision" with source control is to move from the "provider model" (where there are generalized Operations that point an abstracted provider) to repository-specific Operations. For example, you would do this:
* Create a Username/Password Resource Credential
* Use Git-specific operations, like Git-Checkout, Git-Pull, etc, that would work much closer to how git.exe works
* These operations could then have flags/options to indicate whether or not to pull submodules, etc.

There are still some challenges to our idea, for example, where would you specify the .exe path (obviously you don’t want this in every operation)? Our idea is that you would define a variable ($GitExePath), and if that is set, then the operation would look that variable up and use it.  This is how we are handling other paths, like $MsBuildPath and $NugetExePath.

As always, we welcome feedback on this. It’s not technically challenging, but coming up with a model that works is important of course.

**Comment by kmcgain** [comment]
I think this makes sense. It would be quite hard to maintain the existing abstraction and fully support git. 

Having a proper password resource would be useful, currently I have to use basic auth style urls for repositories.

If you stick with individual providers being extensions can you not add a configuration variable on the extension itself to be configured from administration? Ideally you would only have to define it if the extension is unable to discover it automatically based on default install paths / path env variable.

Ideally you would also support log, diff, show, reflog so we can automatically produce release notes, get approvals on specific change sets etc

**Comment by stevedennis** [comment]
Just an update... we've made good progress on this, and will have it available in BuildMaster 5.6 (shipping Nov-18); the existing Git/GitHub extensions will be renamed to LegacyGit and LegacyGitHub, and will be the only ones that contain the "legacy Providers".

We don't have anything published yet, but the new home for the Git stuff will be here: https://github.com/Inedo/inedox-git
